### ISSUE TITLE
NoLogin option

### ISSUE THREAD

**Issue by mrekin** [AlexSciFier/neonlink#10]
Hi!
Can you explain how to use this option?
I register an user, set in settings NoLogin option, then logout.
Login form still here and I have to login again. Option in setting enabled.

Version 1.2.1 installed with docker-compose.

p/s: there was problems with binding sqlite file, have to change in compose file
```
  volumes:
      - type: bind
        source: {path}l
        target: {path}
```

**Comment by AlexSciFier** [comment]
Hi! NoLogin option is fixed in 1.2.2 update.
To bind sqlite file you first need to create sqlite file on your host machine, and then provide path in docker-compose file.

**Comment by mrekin** [comment]
Works in 1.2.2, thanks.

About file
Created file by 'touch filename'
Updated docker-compose.yml with absolute path to file
```   
 volumes:
      - /home/user/bookmarks.sqlite:/app/server/db/bookmarks.sqlite
 ```
- error at docker starting something like "you try to bind file to folder or folder to file"

After changing to

```
volumes:
   - type: bind
      source: /home/user/bookmarks.sqlite
      target: /app/server/db/bookmarks.sqlite

```
works as expected

docker-compose version 1.29.2
