### ISSUE TITLE
Neonlink stopped working

### ISSUE THREAD

**Issue by harkfujow** [AlexSciFier/neonlink#103]
My Neonlink instance decided to give up the ghost today. It simply will not start. I've uninstalled and reinstalled a few times. Here is the yaml I'm trying to get to work.

version:  #"3.8"

```
services:
  neonlink:
    image: alexscifier/neonlink
    container_name: neonlink
    # user: 1000:1000 # optional
    volumes:
      - /DATA/AppData/neonlink/data:/app/data
      - /DATA/AppData/neonlink/background:/app/public/static/media/background
    restart: unless-stopped
    environment:
      FASTIFY_PLUGIN_TIMEOUT: 120000 # optional: change to 0 if AVV_ERR_READY TIMEOUT error is occured
    ports:
      - "3080:3333"

```
I've deleted the neonlink folder, after copying the bookmarks.sqlite file to another folder in the (hopefully not misplaced) hope that I can preserve my bookmarks.

Here is my current error:

```
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at AppSecrets.load (file:///app/contexts/appSecrets.js:34:12)
at async initializeConfig (file:///app/plugins/001-config.js:22:5)
at async fp.fastify (file:///app/plugins/001-config.js:86:3)

```
I get the same error when I uncomment the user line.
