### ISSUE TITLE
Can no longer save bookmarks

### ISSUE THREAD

**Issue by harkfujow** [AlexSciFier/neonlink#105]
This just cropped up out of nowhere. I'm running Neonlink in a Docker container. Everything was running smoothly. Now, for some reason, I can no longer save any bookmarks. I'm seeing this is my logs:

> msg=Invalid URL
> 2024/08/28 12:53PM 50 pid=1 hostname=81cadad50474 reqId=req-1v req={"method":"POST","url":"/api/bookmarks","hostname":"192.168.1.114:3080","remoteAddress":"192.168.1.19","remotePort":46664} res={"statusCode":500} err={"type":"SqliteError","message":"attempt to write a readonly database","stack":"SqliteError: attempt to write a readonly database\n    at BookmarksStore.addItem (file:///app/db/sqlite/stores/bookmarks.js:20:8)\n    at Object.<anonymous> (file:///app/routes/api/bookmarks/index.js:139:42)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","code":"SQLITE_READONLY"} msg=attempt to write a readonly database

I've made no changes aside from updating the Docker container recently. I don't know why the error above is referencing 192.168.1.19. I have nothing on that IP address. This is my docker-compose:

```
name: neonlink
services:
  neonlink:
    cpu_shares: 90
    command:
      - node
      - server.js
    deploy:
      resources:
        limits:
          memory: 7801M
    environment:
      - FASTIFY_ADDRESS=0.0.0.0
      - FASTIFY_BODY_LIMIT=5242880
      - FASTIFY_LOG_LEVEL=error
      - FASTIFY_PLUGIN_TIMEOUT=120000
      - NODE_ENV=production
      - NODE_VERSION=20.11.0
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PORT=3333
      - YARN_VERSION=1.22.19
    image: alexscifier/neonlink:latest
    ports:
      - target: 3333
        published: "3080"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/neonlink/data
        target: /app/data
      - type: bind
        source: /DATA/AppData/neonlink/background
        target: /app/public/static/media/background
    x-casaos:
      envs:
        - container: FASTIFY_PLUGIN_TIMEOUT
          description:
            en_us: ""
        - container: PATH
          description:
            en_us: ""
        - container: NODE_VERSION
          description:
            en_us: ""
        - container: YARN_VERSION
          description:
            en_us: ""
        - container: NODE_ENV
          description:
            en_us: ""
        - container: PORT
          description:
            en_us: ""
        - container: FASTIFY_BODY_LIMIT
          description:
            en_us: ""
        - container: FASTIFY_ADDRESS
          description:
            en_us: ""
        - container: FASTIFY_LOG_LEVEL
          description:
            en_us: ""
      image: ""
      ports:
        - container: "3333"
          description:
            en_us: ""
      volumes:
        - container: /app/data
          description:
            en_us: ""
        - container: /app/public/static/media/background
          description:
            en_us: ""
    devices: []
    cap_add: []
    network_mode: neonlink_default
    privileged: false
    container_name: ""
    hostname: ""
x-casaos:
  architectures:
    - amd64
  author: CasaOS User
  category: unknown
  description:
    en_us: ""
  developer: unknown
  hostname: ""
  icon: ""
  image: null
  index: /
  is_uncontrolled: false
  main: neonlink
  port_map: "3080"
  scheme: http
  store_app_id: neonlink
  tagline:
    en_us: This is a compose app converted from a legacy app (CasaOS v0.4.3 or
      earlier)
  thumbnail: ""
  tips:
    custom: This is a compose app converted from a legacy app (CasaOS v0.4.3 or
      earlier)
  title:
    custom: ""
    en_us: neonlink
```

Any idea what I can do to fix this? 

Thanks
