### ISSUE TITLE
How can I use local images as background?

### ISSUE THREAD

**Issue by basicallynewbie** [AlexSciFier/neonlink#2]
It says I can "Upload" or choose background image in the settings. But when click the + button, I can only add image url, no other upload options.
![火狐截图_2022-09-17T15-49-31 055Z](https://user-images.githubusercontent.com/107107611/190865321-b0dc1bb7-5e85-4b70-ad17-ce7ba00aa9a9.png)

Here is my docker compose:
```
version: "3.8"
services:
  neonlink:
    image: alexscifier/neonlink
    container_name: neonlink
    volumes:
      - /home/me/docker/neonlink/bookmarks.sqlite:/app/server/db/bookmarks.sqlite
    restart: always
    ports:
      - "3333:3333"
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external: true
```
