### ISSUE TITLE
arm64 1.2.7 docker wont starting

### ISSUE THREAD

**Issue by abaranyi** [AlexSciFier/neonlink#39]
Here is my docker file:

```
version: "3.8"

services:
  neonlink:
    image: alexscifier/neonlink:latest-arm64v8
    container_name: neonlink
    volumes:
      - ./bookmarks.sqlite:/app/db/bookmarks.sqlite
    restart: unless-stopped
    ports:
      - "127.0.0.1:3333:3333"
```

when I try to start I got the following error:
```
$ docker-compose up
Creating network "neonlink_default" with the default driver
Creating neonlink ... done
Attaching to neonlink
neonlink    | exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

when I change back to 1.2.6 everything working fine.
