### ISSUE TITLE
v1.3.0 not starting

### ISSUE THREAD

**Issue by choque88** [AlexSciFier/neonlink#46]
Since updating to v1.3.0, the container won't start with the following error message

```bash
neonlink  | TypeError: Cannot open database because the directory does not exist
neonlink  |     at new Database (/app/node_modules/better-sqlite3/lib/database.js:59:9)
neonlink  |     at Object.<anonymous> (/app/db/connect.js:2:10)
neonlink  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
neonlink  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
neonlink  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
neonlink  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
neonlink  |     at Module.require (node:internal/modules/cjs/loader:1100:19)
neonlink  |     at require (node:internal/modules/cjs/helpers:108:18)
neonlink  |     at Object.<anonymous> (/app/app.js:5:18)
neonlink  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
neonlink  | /app/node_modules/better-sqlite3/lib/database.js:59
neonlink  |             throw new TypeError('Cannot open database because the directory does not exist');
```

Here's my docker-compose.yml for reference
```yaml
version: "3.8"

services:
  neonlink:
    image: alexscifier/neonlink
    container_name: neonlink
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bookmarks.sqlite:/app/db/bookmarks.sqlite
      - ./background:/app/public/static/media/background
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.neonlink-secure.entrypoints=websecure
      - traefik.http.routers.neonlink-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.neonlink-secure.service=neonlink
      - traefik.http.routers.neonlink-secure.middlewares=safe-ipwhitelist@file
      - traefik.http.services.neonlink.loadbalancer.server.port=3333

networks:
  proxy:
    external: true
```
