### ISSUE TITLE
Installation on Synology NAS

### ISSUE THREAD

**Issue by Tritschla** [AlexSciFier/neonlink#6]
Hi, I've tried to install Neonlink as a docker image onto my Synology NAS but I'm not sure how to configure it to get it working.
May you have a idea, how this can be achieved via the Synology DSM gui?

**Comment by AlexSciFier** [comment]
Hi, thank you for your feedback. Sorry but i dont have Synology NAS and i don't know how to setup docker on it. But i can recommend you to install Portainer first. It's a web based gui for docker.

1. Install Portainer ([This is official guide for Synology](https://www.portainer.io/blog/how-to-install-portainer-on-a-synology-nas) but you can find any other guides in internet)
2. Create empty `bookmarks.sqlite` file somewhere
3. In Portainer create new stack
4. Paste this
```
version: "3.8"

services:
  neonlink:
    image: alexscifier/neonlink
    volumes:
      - ./bookmarks.sqlite:/app/server/db/bookmarks.sqlite
    restart: always
    ports:
      - "80:3333"
```
 - Replace ./bookmarks.sqlite to your file path e.g. /volume1/docker/bookmarks.sqlite
 - Replace 80 with any free port
