### ISSUE TITLE
Error: EACCES: permission denied, open '/app/data/secrets.json'

### ISSUE THREAD

**Issue by SAM4191** [AlexSciFier/neonlink#65]
I use the docker-compose file supplied on amd64 and just changed the port binding to 3333:3333 .

```
version: "3.8"

services:
  neonlink:
    image: alexscifier/neonlink
    container_name: neonlink
    volumes:
      - ./data:/app/data
      - ./background:/app/public/static/media/background
    restart: unless-stopped
    ports:
      - "3333:3333"
```
Also tried it with
`sudo docker run -p 3333:3333 -v ./data:/app/data -v ./backgrounds:/app/public/static/media/background alexscifier/neonlink:latest
`

I tried a few different versions.
When I run the docker image with docker-compose I get the Error below.

```
[Error: EACCES: permission denied, open '/app/data/secrets.json'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/data/secrets.json'
}
```
When I manually create the secrets.json with the content "{}" I get a similar Error about settings.json.
With secrets.json and settings.json I get the following Error.

```
Config plugin initialization completed.
SqliteError: unable to open database file
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:63:26)
    at new SqliteManager (file:///app/db/sqlite/database.js:86:15)
    at initializeDatabaseManager (file:///app/plugins/010-database.js:11:10)
    at async initializeDatabase (file:///app/plugins/010-database.js:77:27)
    at async fp.fastify (file:///app/plugins/010-database.js:89:29) {
  code: 'SQLITE_CANTOPEN'
}
```

There are no files in data or background (without manually creating them).
